### ISSUE TITLE
Some PoliCheck reported bugs in the regex test sets

### ISSUE THREAD

**Issue by Cosifne** [dotnet/runtime-assets#212]
So in Roslyn, we are using the same test [file](https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/CSharpTest/EmbeddedLanguages/RegularExpressions/Regex_RealWorldPatterns.json) as [here](https://github.com/dotnet/runtime-assets/blob/main/src/System.Text.RegularExpressions.TestData/Regex_RealWorldPatterns.json) to test a regex engine.
But we received some PoliCheck bugs related to the words in the test sets.

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1450263/
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1450268/
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1450266/
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1450264/
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1450259/

I mark all of them as resolved now because it is only used for testing purposes but I want to have a double-check with you, do we allow PoliCheck bugs in the test asset file?

**Comment by stephentoub** [comment]
They're false positives,  e.g. that first entry is actually a fine French word, not English derogatory slang.
