### ISSUE TITLE
Turn on github actions for this repository

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime-assets#309]
I have a (slightly broken) github action in my fork that checks weekly for updates of tzdb and opens a pr, I would like to move it here but I can't until actions are enabled here.

**Comment by lewing** [comment]
cc @akoeplinger

**Comment by akoeplinger** [comment]
I don't have permissions but I asked in FR.

**Comment by akoeplinger** [comment]
@ViktorHofer can you please turn on actions?

**Comment by ViktorHofer** [comment]
Enabled with the same settings as in dotnet/runtime.
